projects/Blog/app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length
from flask_pagedown.fields import PageDownField


class ProfileForm(FlaskForm):
    nickname = StringField('nickname', validators=[Length(0, 7)])
    about_me = PageDownField('about me', validators=[Length(0, 140)])

class PostForm(FlaskForm):
    body = TextAreaField('Create New Post', validators=[DataRequired()])
    title = StringField('Title', validators=[Length(1, 20)])
    # outline = StringField('Abstract', validators=[Length()])
    save_draft = SubmitField('Save Draft')
    submit = SubmitField('Publish')

class EditpostForm(FlaskForm):
    title = StringField('Title', validators=[Length(1, 20)])
    body = TextAreaField('Edit Content', validators=[DataRequired()])
    update = SubmitField('Update')
    submit = SubmitField('Publish')
    save_draft = SubmitField('Save')

class CommentForm(FlaskForm):
    body = PageDownField('Comment', validators=[DataRequired()])

class ReplyForm(FlaskForm):
    body = PageDownField('Reply', validators=[DataRequired()])

class SearchForm(FlaskForm):
    search = StringField('Search', validators=[DataRequired()])

projects/Blog/app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views, errors
from ..models import Permission

@user.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

projects/Blog/app/user/views.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, abort, make_response, g, current_app
from flask_login import current_user, login_required

from .. import db
from . import user
from .forms import ProfileForm, PostForm, CommentForm, ReplyForm, SearchForm, EditpostForm
from ..models import User, Post, Comment, Like, Permission, Admin
from ..decorators import permission_required


@user.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.now()
        db.session.add(current_user)
        db.session.commit()
    g.search_form = SearchForm()

@user.route('/')
@user.route('/index')
def index():
    notice = Admin.query.order_by(Admin.timestamp.desc()).first()
    if notice:
        notice=notice.notice
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'],
        error_out=False
    )
    # posts = pagination.items
    posts = [post for post in pagination.items if post.draft==False]
    return render_template('user/index.html',
                           title = 'Homepage',
                           posts=posts,
                           notice=notice,
                           pagination=pagination)

@user.route('/user/<nickname>')
# @login_required
def users(nickname):
    user = User.query.filter_by(nickname = nickname).first()
    if user == None:
        flash('Not find：' + nickname)
        return redirect(url_for('user.index'))
    posts = user.posts.order_by(Post.timestamp.desc()).all()
    posts = [post for post in posts if post.draft == False]
    return render_template('user/user.html',
                           user=user,
                           posts=posts,
                           title='Personal Profile')

@user.route('/edit_profile', methods=['GET','POST'])
@login_required
def edit_profile():
    form = ProfileForm()
    if form.validate_on_submit():
        current_user.nickname = form.nickname.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        flash('Change successful!')
        return redirect(url_for('user.users',nickname=current_user.nickname))
    else:
        form.nickname.data = current_user.nickname
        form.about_me.data = current_user.about_me
    return render_template('user/editprofile.html',
                           form=form,
                           title='Edit Profile')

@user.route('/write', methods=['GET','POST'])
def write():
    form = PostForm()
    if current_user.operation(Permission.WRITE_ARTICLES) and \
            form.validate_on_submit():
        if 'save_draft' in request.form and form.validate():
            post = Post(body=form.body.data,
                        title=form.title.data,
                        draft= True,
                        author = current_user._get_current_object())
            db.session.add(post)
            flash('Save successful!')
        elif 'submit' in request.form and form.validate():
            post = Post(body=form.body.data,
                        title=form.title.data,
                        author=current_user._get_current_object())
            db.session.add(post)
            flash('Publish successful!')
        return redirect(url_for('user.write'))
    return render_template('user/write.html',
                           form=form,
                           post=form.body.data,
                           title='Write Posts')

@user.route('/draft/')
@login_required
def draft():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'],
        error_out=False
    )
    posts = pagination.items
    drafts = [post for post in posts if post.draft==True]

    return render_template('user/draft.html',
                           title='Draft',
                           pagination=pagination,
                           drafts=drafts)

@user.route('/delete-draft/<int:id>')
@login_required
def delete_draft(id):
    draft = Post.query.get_or_404(id)
    draft.disabled = True
    db.session.add(draft)
    flash('Delete successful!')
    return redirect(url_for('user.draft'))


@user.route('/post/<int:id>', methods=['GET','POST'])
def post(id):
    post = Post.query.get_or_404(id)
    post.view_num += 1
    db.session.add(post)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          post=post, unread=True,
                          author=current_user._get_current_object())
        db.session.add(comment)
        flash('Your comment has been published successfully.')
        return redirect(url_for('user.post', id=post.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() - 1) / \
               current_app.config['COMMENTS_PER_PAGE'] + 1
    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=current_app.config['COMMENTS_PER_PAGE'],
        error_out=False
    )
    comments = pagination.items
    return render_template('user/post.html', posts=[post],
                           title=post.title, id=post.id,
                           post=post, form=form,
                           comments=comments,
                           pagination=pagination)

@user.route('/like/<int:id>')
@login_required
def like(id):
    post = Post.query.get_or_404(id)

    if post.like_num.filter_by(liker_id=current_user.id).first() is not None:
        flash('You\'ve liked it.')
        return redirect(url_for('user.post', id=post.id))
    like = Like(post=post, unread=True,
                user=current_user._get_current_object())
    db.session.add(like)
    flash('Like successful!')
    return redirect(url_for('user.post', id=post.id))

@user.route('/unlike/<int:id>')
@login_required
def unlike(id):
    post = Post.query.get_or_404(id)
    if post.like_num.filter_by(liker_id=current_user.id).first() is None:
        flash('You have not liked it yet.')
        return redirect(url_for('user.post', id=post.id))
    # like = Like(post=post,
    #             user=current_user._get_current_object())
    else:
        f = post.like_num.filter_by(liker_id=current_user.id).first()
        db.session.delete(f)
        flash('Likes have been cancelled.')
        return redirect(url_for('user.post', id=post.id))

@user.route('/reply/<int:id>', methods=['GET','POST'])
@login_required
def reply(id):
    comment = Comment.query.get_or_404(id)
    post = Post.query.get_or_404(comment.post_id)
    page = request.args.get('page', 1, type=int)
    form = ReplyForm()
    if form.validate_on_submit():
        reply_comment = Comment(body=form.body.data,
                                unread=True,
                                post=post,comment_type='reply',
                                reply_to=comment.author.nickname,
                                author=current_user._get_current_object())
        db.session.add(reply_comment)
        flash('Your reply has been published.')
        return redirect(url_for('user.post', id=comment.post_id, page=page))
    return render_template('user/reply.html',
                           form=form,
                           comment=comment,
                           title='Reply')

@user.route('/recover/<int:id>')
@login_required
def recover(id):
    comment = Comment.query.get_or_404(id)
    post_id = comment.post_id
    comment.disabled = False
    db.session.add(comment)
    return redirect(url_for('user.post',id=post_id))

@user.route('/delate/<int:id>')
@login_required
def delate(id):
    comment = Comment.query.get_or_404(id)
    post_id = comment.post_id
    comment.disabled = True
    db.session.add(comment)
    return redirect(url_for('user.post',id=post_id))

@user.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author and \
        not current_user.operation(Permission.ADMINISTER):
        abort(403)
    form = EditpostForm()
    if form.validate_on_submit():
        post.body = form.body.data
        if post.draft == True:
            if 'save_draft' in request.form and form.validate():
                db.session.add(post)
                flash('Save successfully!')
            elif 'submit' in request.form and form.validate():
                post.draft = False
                db.session.add(post)
                flash('Publish successfully!')
            return redirect(url_for('user.edit', id=post.id))
        else:
            db.session.add(post)
            flash('Update successfully!')
            return redirect(url_for('user.post', id=post.id))
    form.title.data = post.title
    form.body.data = post.body
    return render_template('user/editpost.html',
                           form=form,
                           post=post,
                           title='Edit Posts')

@user.route('/follow/<nickname>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(nickname):
    user = User.query.filter_by(nickname=nickname).first()
    if user is None:
        flash('Invalid user')
        return redirect(url_for('user.index'))
    if current_user.is_following(user):
        flash('You are already following this user.')
        return redirect(url_for('user.users', nickname=nickname))
    current_user.follow(user)
    flash('You have followed %s。' % nickname)
    return redirect(url_for('user.users', nickname=nickname))

@user.route('/unfollow/<nickname>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(nickname):
    user = User.query.filter_by(nickname=nickname).first()
    if user is None:
        flash('Invalid user')
        return redirect(url_for('user.index'))

projects/Blog/app/templates/user/draft.html
{% extends "base.html" %}

{% block content %}
<h1>Draft</h1><hr>
{% if drafts %}
{% for draft in drafts %}
{% if draft.disabled != True %}
    <ol>
        <li>
            <h4>{{ draft.title }}</h4>
            <p>
                {% if draft.body_html %}
                    {{ draft.body_html | safe | truncate(100) }}
                {% else %}
                    {{ draft.body | truncate(100) }}
                {% endif %}
            </p>
            <a class="taga" href="{{ url_for('user.delete_draft',id=draft.id) }}"><span class="label label-danger">Delete</span></a>
            <a class="taga" href="{{ url_for('user.edit',id=draft.id) }}"><span class="label label-primary">Edit</span></a>
        </li><hr>
    </ol>
{% endif %}
{% endfor %}
{% endif %}
{% endblock %}

projects/Blog/app/templates/user/editpost.html
{% extends "base.html" %}

{%block styles%}
{{super()}}
<link rel="stylesheet" href="{{ url_for('static',filename='editormd/css/editormd.css') }}"/>
{% endblock %}

{% block content %}
<h1>Edit Post</h1><hr>
<form action="" method="post" name="editpost">
    {{form.hidden_tag()}}

        Title<br>
        {{form.title(class="form-control")}}<br>
        {% for error in form.title.errors %}
            <span style="color: red;">[{{error}}]</span>
        {% endfor %}<br>
        Content<br>
        <div id="editormd">
            {{form.body(style="display:none;")}}<br>
            {% for error in form.body.errors %}
                <span style="color: red;">[{{error}}]</span>
            {% endfor %}<br>
        </div>
        {% if post.draft==True %}
        {{ form.submit(class="btn btn-default") }}<br><br>
        {{ form.save_draft(class="btn btn-default") }}
        {% else %}
        {{ form.update(class="btn btn-default") }}
        {% endif %}


</form>
{% endblock %}

{% block scripts %}
{{super()}}
<script src="{{ url_for('static',filename='editormd/editormd.min.js') }}"></script>
    <script type="text/javascript">
        var testEditor;
        $(function () {
            testEditor = editormd("editormd", {
                syncScrolling: "single",
                width: "100%",
                height: "550px",
                path: "{{ url_for('static',filename='editormd/lib/') }}"
            });
        });
    </script>
{% endblock %}

projects/Blog/app/templates/user/editprofile.html
{% extends "base.html" %}

{% block content %}
<h1>Edit Profile</h1><hr>
<form action="" method="post" name="edit">
    <p>
        {{form.hidden_tag()}}
        Your nickname：<br>
        {{form.nickname(class="form-control")}}<br>
        {% for error in form.nickname.errors %}
            <span style="color: red;">{{error}}</span>
        {% endfor %}<br>
        Personal Signature：<br>
        {{form.about_me(class="form-control",rows="4")}}<br>
        {% for error in form.about_me.errors %}
            <span style="color: red;">{{error}}</span>
        {% endfor %}<br>
    </p>
    <p><input class="btn btn-default" type="submit" value="保存资料"></p>
</form>
{% endblock %}

projects/Blog/app/templates/user/follow.html
{% extends "base.html" %}
{% import "_pages.html" as page %}

{% block content %}
<div class="row clearfix">
    <div class="col-md-8 column">
        <ul class="nav nav-tabs">
            <li {% if show_followed %}class="active"{% endif %}>
                 <a href="{{ url_for('user.show_follower',nickname=user.nickname) }}">Followers</a>
            </li>
            <li {% if not show_followed %}class="active"{% endif %}>
                 <a href="{{ url_for('user.show_followed',nickname=user.nickname) }}">Following</a>
            </li>
        </ul>
        <br>
        {% for follow in follows %}
        <ul class="list-group">
            <li class="list-group-item">
                <a href="{{ url_for('user.users',nickname=follow.user.nickname) }}">{{ follow.user.nickname }}</a>
                <span class="right">{{ moment(follow.timestamp).fromNow() }}</span>
                {% if current_user.operation(Permission.FOLLOW) and user != current_user %}
                    {% if not current_user.is_following(user) %}
                    <a class="right" href="{{ url_for('user.follow', nickname=user.nickname) }}">Follow</a>
                    {% else %}
                    <a class="right" href="{{ url_for('user.unfollow', nickname=user.nickname) }}">Unfollow</a>
                    {% endif %}
                {% endif %}
            </li>
        </ul>
        {% endfor %}
        <hr>
        <div class="pagination">
            {{ page.pages(pagination, 'user.follows', nickname=user.nickname) }}
        </div>
        <hr>
    </div>
    <div class="col-md-4 column">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h4 class="panel-title">Recommended Posts</h4>
            </div>
            <div class="panel-body">
                {% if current_user == user %}
                {% for post in current_user.followed_posts %}
                {% if not post.disabled and not post.draft %}
                <a href="{{ url_for('user.post', id=post.id) }}">
                    {{ post.title }}
                </a><hr>
                {% endif %}
                {% endfor %}
                {% else %}
                {% for post in user.posts %}
                {% if not post.disabled and not post.draft %}
                <a href="{{ url_for('user.post', id=post.id) }}">
                    {{ post.title }}
                </a><hr>
                {% endif %}
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

projects/Blog/app/templates/user/index.html
{% extends "base.html" %}
{% import "_pages.html" as page %}

{% block content %}
<div class="panel panel-warning">
    <div class="panel-heading">
        <h4>
        Hello,
        {% if current_user.is_authenticated %}
            {{current_user.nickname}}。{% if notice%}{{notice}}{%else%}Start your creation and let the world know you.{%endif%}
        {% else %}
            Adventurer, why wander alone? Join us and share your story.
        {% endif %}
        </h4><br>
        {% if current_user.operation(Permission.WRITE_ARTICLES) %}
        <a href="{{url_for('user.write')}}">
            <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-pencil"></span> Create New Post
            </button>
        </a> |
        <a href="{{ url_for('user.draft') }}">
            <button type="button" class="btn btn-default btn-sm">
              <span class="glyphicon glyphicon-file"></span> Draft
            </button>
        </a>
        {% endif %}
        {% if current_user.operation(Permission.ADMINISTER) %}
        |
        <a href="{{ url_for('admin.index') }}">
            <button type="button" class="btn btn-default btn-sm">
              <span class="glyphicon glyphicon-cog"></span> Administer
            </button>
        </a>
        {% endif %}
    </div>
</div>
<hr>
{% if posts %}
{% for post in posts %}
{% if not post.disabled %}
{% include "_posts.html" %}<hr>
{% endif %}
{% endfor %}
<div class="pagination">
{{ page.pages(pagination, 'user.index') }}
</div>
{% endif %}
{% endblock %}

projects/Blog/app/templates/user/post.html
{% extends "base.html" %}
{% import "_pages.html" as page %}

{% block content %}
<div>
{% if posts %}
{% for post in posts %}
<h3 align="center">{{ post.title }}</h3>
<p align="center">Author：<a href="{{ url_for('user.users', nickname=post.author.nickname) }}">{{ post.author.nickname }}</a> </p>

{% if post.body_html %}
    {{ post.body_html | safe }}
{% else %}
    {{post.body }}
{% endif %}

<i class="right">{{ moment(post.timestamp).fromNow() }} Publish</i>
<br>
{% if current_user.is_authenticated %}
{% if post.like_num.filter_by(liker_id=current_user.id).first() == None %}
    <a href="{{ url_for('user.like',id=post.id) }}" class="btn btn-info btn-lg">
      <span class="glyphicon glyphicon-thumbs-up"></span> Like|{{ post.like_num.count() }}
    </a>
{% else %}
    <a href="{{ url_for('user.unlike',id=post.id) }}" class="btn btn-info btn-lg">
      <span class="glyphicon glyphicon-thumbs-down"></span> Unlike|{{ post.like_num.count() }}
    </a>
{% endif %}
{% else %}
    <a href="{{ url_for('user.like',id=post.id) }}" class="btn btn-info btn-lg">
      <span class="glyphicon glyphicon-thumbs-up"></span> Like|{{ post.like_num.count() }}
    </a>
{% endif %}
{% endfor %}
{% endif %}
<hr>

<h3><i>{{ post.comments.count() }} comments</i></h3>
<div>
    {% for comment in comments %}
    {% if not comment.disabled %}
    <ul class="list-group">
        {% if comment.comment_type=='comment' %}
        <li class="list-group-item">
            <div>
                <img src="{{comment.author.gravatar(size=30)}}">
                <a href="{{url_for('user.users', nickname=comment.author.nickname)}}">
                    {{ comment.author.nickname }}
                </a>:
                {% if current_user.nickname == post.author.nickname %}
                    <h4><span class="right label label-danger">
                        <a class="taga" href="{{ url_for('user.delate',id=comment.id) }}">Delete</a>
                    </span></h4>
                {% endif %}
                <span class="right">{{ moment(comment.timestamp).fromNow() }}Publish</span>
                <span class="right"><a href="{{ url_for('user.reply',id=comment.id) }}">Reply</a> </span>
            </div>
            <div class="comments">
                <p>
                {% if comment.body_html %}
                    {{ comment.body_html | safe }}
                {% else %}
                    {{ comment.body }}
                {% endif %}
                </p>
            </div>
        </li>
        {% endif %}
        {% if comment.comment_type=='reply' %}
        <li class="list-group-item">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-comment"></span> Reply to {{ comment.reply_to }}:
                    </h3>
                </div>
            </div>
            <div>
                <img src="{{comment.author.gravatar(size=30)}}">
                <a href="{{url_for('user.users', nickname=comment.author.nickname)}}">
                    {{ comment.author.nickname }}
                </a>:
                {% if current_user.nickname == post.author.nickname %}
                    <h4><span class="right label label-danger">
                        <a class="taga" href="{{ url_for('user.delate',id=comment.id) }}">Delete</a>
                    </span></h4>
                {% endif %}
                <span class="right">{{ moment(comment.timestamp).fromNow() }}Publish</span>
                <span class="right"><a href="{{ url_for('user.reply',id=comment.id) }}">Reply</a> </span>
            </div>
            <div class="comments">
                <p>
                {% if comment.body_html %}
                    {{ comment.body_html | safe }}
                {% else %}
                    {{ comment.body }}
                {% endif %}
                </p>
            </div>
        </li>
        {% endif %}
    </ul>
    {% else %}
        {% if current_user.nickname == post.author.nickname %}
        <ul class="list-group">
            {% if comment.comment_type=='comment' %}
            <li class="list-group-item">

                <div>
                    <img src="{{comment.author.gravatar(size=30)}}">
                    <a href="{{url_for('user.users', nickname=comment.author.nickname)}}">
                        {{ comment.author.nickname }}
                    </a>:
                        <h4><span class="right label label-default">
                            <a class="tags" href="{{ url_for('user.recover',id=comment.id) }}">Recover</a>
                        </span></h4>
                    <span class="right">{{ moment(comment.timestamp).fromNow() }}Publish</span>
                </div>
                <div class="comments">
                    <p>
                    {% if comment.body_html %}
                        {{ comment.body_html | safe }}
                    {% else %}
                        {{ comment.body }}
                    {% endif %}
                    </p>
                </div>
            </li>
            {% endif %}
            {% if comment.comment_type=='reply' %}
            <li class="list-group-item">
                <div>
                    <img src="{{comment.author.gravatar(size=30)}}">
                    <a href="{{url_for('user.users', nickname=comment.author.nickname)}}">
                        {{ comment.author.nickname }}
                    </a>:
                        <h4><span class="right label label-danger">
                            <a class="taga" href="{{ url_for('user.recover',id=comment.id) }}">Recover</a>
                        </span></h4>
                    <span class="right">{{ moment(comment.timestamp).fromNow() }}Publish</span>
                </div>
                <div class="comments">
                    <p>
                    {% if comment.body_html %}
                        {{ comment.body_html | safe }}
                    {% else %}
                        {{ comment.body }}
                    {% endif %}
                    </p>
                </div>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    {% endif %}
    {% endfor %}
</div>

<div class="pagination">
    {{ page.pages(pagination, 'user.post', fragment='#comments', id=posts[0].id) }}
</div>
<hr>
<form action="" method="post" name="comment">
    {{form.hidden_tag()}}
    <h4>评论</h4>
    {{form.body(class="form-control",rows="3")}}<br>
    {% for error in form.body.errors %}
        <span style="color: red;">[{{error}}]</span>
    {% endfor %}<br>
    <p>
        {% if current_user.is_authenticated %}
        <input class="btn btn-default" type="submit" value="发表">
        {% else %}
        <a href="{{ url_for('auth.login') }}">
            <h4>You are not logged in yet, you will go to the login webpage next!</h4>
        </a>
        {% endif %}
    </p>
</form>
</div>
{% endblock %}

projects/Blog/app/templates/user/reply.html
{% extends "base.html" %}

{% block content %}
<h4>Reply{{ comment.author.nickname }}</h4>
<hr>
<div>
    <img src="{{comment.author.gravatar(size=30)}}">
    <a href="{{url_for('user.users', nickname=comment.author.nickname)}}">
        {{ comment.author.nickname }}
    </a>:
</div>
<div class="comments">
    <p>
    {% if comment.body_html %}
        {{ comment.body_html | safe }}
    {% else %}
        {{ comment.body }}
    {% endif %}
    </p>
</div>
<hr>
<form action="" method="post" name="reply">
{{form.hidden_tag()}}
{{form.body(class="form-control",rows="3")}}<br>
{% for error in form.body.errors %}
    <span style="color: red;">[{{error}}]</span>
{% endfor %}<br>
<p>
    <input class="btn btn-default" type="submit" value="发表">
</p>
</form>
{% endblock %}

projects/Blog/app/templates/user/search_results.html
{% extends "base.html" %}

{% block content %}
<h3>"{{query}}"'s results：</h3><hr>
{% for post in posts %}
{% if post.draft == False %}
{% include '_posts.html' %}
{% endif %}
{% endfor %}
{% endblock %}

projects/Blog/app/templates/user/user.html
{% extends "base.html" %}

{% block content %}
<table>
    <tr valign="top">
        <td><img class="images" src="{{user.gravatar(200)}}"></td>
        <td>
            <h1>{{user.nickname}}'s profile</h1>
            {% if user.about_me %}<p>{{user.about_me}}</p>{% endif %}
            {% if user.last_seen %}<p><i>Last login time：{{moment(user.last_seen).format('LL')}}</i></p>{% endif %}
            {% if user == current_user %}
            <p>
            <a href="{{url_for('user.edit_profile')}}">
            <button type="button" class="btn btn-default btn-sm">
              <span class="glyphicon glyphicon-cog"></span> Modify profile
            </button>
            </a>
            </p>
            {% endif %}
            {% if current_user.operation(Permission.FOLLOW) and user != current_user %}
                {% if not current_user.is_following(user) %}
                <a href="{{ url_for('user.follow', nickname=user.nickname) }}">
                    <button type="button" class="btn btn-default btn-sm">
                      <span class="glyphicon glyphicon-star"></span> Follow
                    </button>
                </a>
                {% else %}
                <a href="{{ url_for('user.unfollow', nickname=user.nickname) }}">
                    <button type="button" class="btn btn-default btn-sm">
                      <span class="glyphicon glyphicon-star-empty"></span> Unfollow
                    </button>
                </a>
                {% endif %}
            {% endif %}
            <a href="{{ url_for('user.follows', nickname=user.nickname) }}">
                Followers：
            </a><span>{{ user.followers.count() }}</span>
            <a href="{{ url_for('user.follows', nickname=user.nickname) }}">
                Following：
            </a><span>{{ user.followed.count() }}</span>
            {% if current_user.is_authenticated and user != current_user and
                user.is_following(current_user) %}
            | <span>Followed you</span>
            {% endif %}

            {% if current_user != user %}
            <a href="{{ url_for('message.write_letter',id=user.id) }}" class="btn btn-info">
              <span class="glyphicon glyphicon-envelope"></span> Seed message
            </a>
            {% endif %}
        </td>
    </tr>
</table>
<br>
<h3>Published All Posts</h3>
<hr>
{% if posts %}
{% for post in posts %}
{% if not post.disabled %}
{% include "_posts.html" %}<hr>
{% endif %}
{% endfor %}
{% endif %}
{% endblock %}

projects/Blog/app/templates/user/write.html
{% extends "base.html" %}

{%block styles%}
{{super()}}
<link rel="stylesheet" href="{{ url_for('static',filename='editormd/css/editormd.css') }}"/>
{% endblock %}
{% block content %}

<h1>Write A Post</h1><hr>
<form action="" method="post" name="write">
    {{form.hidden_tag()}}

        Title<br>
        {{form.title(class="form-control")}}<br>
        {% for error in form.title.errors %}
            <span style="color: red;">[{{error}}]</span>
        {% endfor %}<br>

        Content<br>

        <div id="editormd">
            {{form.body(style="display:none;")}}<br>
            {% for error in form.body.errors %}
                <span style="color: red;">[{{error}}]</span>
            {% endfor %}<br>
        </div>

        {{ form.submit(class="btn btn-default") }}<br><br>
        {{ form.save_draft(class="btn btn-default") }}

</form>
{% if post.body_html %}
    {{ post.body_html | safe }}
{% endif %}
{% endblock %}

{% block scripts %}
{{super()}}
<script src="{{ url_for('static',filename='editormd/editormd.min.js') }}"></script>
    <script type="text/javascript">
        var testEditor;
        $(function () {
            testEditor = editormd("editormd", {
                width: "100%",
                height: "550px",
                syncScrolling: "single",
                path: "{{ url_for('static',filename='editormd/lib/') }}"
            });
        });
    </script>
{% endblock %}